namespace RageCore.Common.Winforms
{
    partial class ExplorerForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ExplorerForm));
            this.MainMenuStrip = new System.Windows.Forms.MenuStrip();
            this.fileToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.MainStatusStrip = new System.Windows.Forms.StatusStrip();
            this.AmountOfItemsInDirectoryLabel = new System.Windows.Forms.ToolStripStatusLabel();
            this.AmountOfItemsSelectedInListViewLabel = new System.Windows.Forms.ToolStripStatusLabel();
            this.MainSplitContainer = new System.Windows.Forms.SplitContainer();
            this.MainTreeView = new System.Windows.Forms.TreeView();
            this.FileImageList = new System.Windows.Forms.ImageList(this.components);
            this.MainListView = new System.Windows.Forms.ListView();
            this.FileNameColumnHeader = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.TypeColumnHeader = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.SizeColumnHeader = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.MainContextMenuStrip = new System.Windows.Forms.ContextMenuStrip(this.components);
            this.extractToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.viewToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.toolStrip1 = new System.Windows.Forms.ToolStrip();
            this.GoBackButton = new System.Windows.Forms.ToolStripButton();
            this.toolStripSeparator1 = new System.Windows.Forms.ToolStripSeparator();
            this.PathTextBox = new System.Windows.Forms.ToolStripTextBox();
            this.RefreshButton = new System.Windows.Forms.ToolStripButton();
            this.toolStripSeparator2 = new System.Windows.Forms.ToolStripSeparator();
            this.SearchTextBox = new System.Windows.Forms.ToolStripTextBox();
            this.SearchButton = new System.Windows.Forms.ToolStripButton();
            this.MainMenuStrip.SuspendLayout();
            this.MainStatusStrip.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.MainSplitContainer)).BeginInit();
            this.MainSplitContainer.Panel1.SuspendLayout();
            this.MainSplitContainer.Panel2.SuspendLayout();
            this.MainSplitContainer.SuspendLayout();
            this.MainContextMenuStrip.SuspendLayout();
            this.toolStrip1.SuspendLayout();
            this.SuspendLayout();
            // 
            // MainMenuStrip
            // 
            this.MainMenuStrip.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.fileToolStripMenuItem});
            this.MainMenuStrip.Location = new System.Drawing.Point(0, 0);
            this.MainMenuStrip.Name = "MainMenuStrip";
            this.MainMenuStrip.Size = new System.Drawing.Size(800, 24);
            this.MainMenuStrip.TabIndex = 0;
            this.MainMenuStrip.Text = "menuStrip1";
            // 
            // fileToolStripMenuItem
            // 
            this.fileToolStripMenuItem.Name = "fileToolStripMenuItem";
            this.fileToolStripMenuItem.Size = new System.Drawing.Size(37, 20);
            this.fileToolStripMenuItem.Text = "File";
            // 
            // MainStatusStrip
            // 
            this.MainStatusStrip.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.AmountOfItemsInDirectoryLabel,
            this.AmountOfItemsSelectedInListViewLabel});
            this.MainStatusStrip.Location = new System.Drawing.Point(0, 428);
            this.MainStatusStrip.Name = "MainStatusStrip";
            this.MainStatusStrip.Size = new System.Drawing.Size(800, 22);
            this.MainStatusStrip.TabIndex = 1;
            this.MainStatusStrip.Text = "statusStrip1";
            // 
            // AmountOfItemsInDirectoryLabel
            // 
            this.AmountOfItemsInDirectoryLabel.Name = "AmountOfItemsInDirectoryLabel";
            this.AmountOfItemsInDirectoryLabel.Size = new System.Drawing.Size(93, 17);
            this.AmountOfItemsInDirectoryLabel.Text = "AmountOfItems";
            // 
            // AmountOfItemsSelectedInListViewLabel
            // 
            this.AmountOfItemsSelectedInListViewLabel.Name = "AmountOfItemsSelectedInListViewLabel";
            this.AmountOfItemsSelectedInListViewLabel.Size = new System.Drawing.Size(137, 17);
            this.AmountOfItemsSelectedInListViewLabel.Text = "AmountOfItemsSelected";
            // 
            // MainSplitContainer
            // 
            this.MainSplitContainer.Cursor = System.Windows.Forms.Cursors.Default;
            this.MainSplitContainer.Dock = System.Windows.Forms.DockStyle.Fill;
            this.MainSplitContainer.Location = new System.Drawing.Point(0, 49);
            this.MainSplitContainer.Name = "MainSplitContainer";
            // 
            // MainSplitContainer.Panel1
            // 
            this.MainSplitContainer.Panel1.Controls.Add(this.MainTreeView);
            // 
            // MainSplitContainer.Panel2
            // 
            this.MainSplitContainer.Panel2.Controls.Add(this.MainListView);
            this.MainSplitContainer.Size = new System.Drawing.Size(800, 379);
            this.MainSplitContainer.SplitterDistance = 266;
            this.MainSplitContainer.TabIndex = 2;
            // 
            // MainTreeView
            // 
            this.MainTreeView.Dock = System.Windows.Forms.DockStyle.Fill;
            this.MainTreeView.ImageIndex = 0;
            this.MainTreeView.ImageList = this.FileImageList;
            this.MainTreeView.Location = new System.Drawing.Point(0, 0);
            this.MainTreeView.Name = "MainTreeView";
            this.MainTreeView.SelectedImageIndex = 0;
            this.MainTreeView.Size = new System.Drawing.Size(266, 379);
            this.MainTreeView.TabIndex = 0;
            this.MainTreeView.BeforeSelect += new System.Windows.Forms.TreeViewCancelEventHandler(this.MainTreeView_BeforeSelect);
            this.MainTreeView.AfterSelect += new System.Windows.Forms.TreeViewEventHandler(this.MainTreeView_AfterSelect);
            // 
            // FileImageList
            // 
            this.FileImageList.ImageStream = ((System.Windows.Forms.ImageListStreamer)(resources.GetObject("FileImageList.ImageStream")));
            this.FileImageList.TransparentColor = System.Drawing.Color.Transparent;
            this.FileImageList.Images.SetKeyName(0, "accept.png");
            this.FileImageList.Images.SetKeyName(1, "add.png");
            this.FileImageList.Images.SetKeyName(2, "anchor.png");
            this.FileImageList.Images.SetKeyName(3, "application.png");
            this.FileImageList.Images.SetKeyName(4, "application_add.png");
            this.FileImageList.Images.SetKeyName(5, "application_cascade.png");
            this.FileImageList.Images.SetKeyName(6, "application_delete.png");
            this.FileImageList.Images.SetKeyName(7, "application_double.png");
            this.FileImageList.Images.SetKeyName(8, "application_edit.png");
            this.FileImageList.Images.SetKeyName(9, "application_error.png");
            this.FileImageList.Images.SetKeyName(10, "application_form.png");
            this.FileImageList.Images.SetKeyName(11, "application_form_add.png");
            this.FileImageList.Images.SetKeyName(12, "application_form_delete.png");
            this.FileImageList.Images.SetKeyName(13, "application_form_edit.png");
            this.FileImageList.Images.SetKeyName(14, "application_form_magnify.png");
            this.FileImageList.Images.SetKeyName(15, "application_get.png");
            this.FileImageList.Images.SetKeyName(16, "application_go.png");
            this.FileImageList.Images.SetKeyName(17, "application_home.png");
            this.FileImageList.Images.SetKeyName(18, "application_key.png");
            this.FileImageList.Images.SetKeyName(19, "application_lightning.png");
            this.FileImageList.Images.SetKeyName(20, "application_link.png");
            this.FileImageList.Images.SetKeyName(21, "application_osx.png");
            this.FileImageList.Images.SetKeyName(22, "application_osx_terminal.png");
            this.FileImageList.Images.SetKeyName(23, "application_put.png");
            this.FileImageList.Images.SetKeyName(24, "application_side_boxes.png");
            this.FileImageList.Images.SetKeyName(25, "application_side_contract.png");
            this.FileImageList.Images.SetKeyName(26, "application_side_expand.png");
            this.FileImageList.Images.SetKeyName(27, "application_side_list.png");
            this.FileImageList.Images.SetKeyName(28, "application_side_tree.png");
            this.FileImageList.Images.SetKeyName(29, "application_split.png");
            this.FileImageList.Images.SetKeyName(30, "application_tile_horizontal.png");
            this.FileImageList.Images.SetKeyName(31, "application_tile_vertical.png");
            this.FileImageList.Images.SetKeyName(32, "application_view_columns.png");
            this.FileImageList.Images.SetKeyName(33, "application_view_detail.png");
            this.FileImageList.Images.SetKeyName(34, "application_view_gallery.png");
            this.FileImageList.Images.SetKeyName(35, "application_view_icons.png");
            this.FileImageList.Images.SetKeyName(36, "application_view_list.png");
            this.FileImageList.Images.SetKeyName(37, "application_view_tile.png");
            this.FileImageList.Images.SetKeyName(38, "application_xp.png");
            this.FileImageList.Images.SetKeyName(39, "application_xp_terminal.png");
            this.FileImageList.Images.SetKeyName(40, "arrow_branch.png");
            this.FileImageList.Images.SetKeyName(41, "arrow_divide.png");
            this.FileImageList.Images.SetKeyName(42, "arrow_down.png");
            this.FileImageList.Images.SetKeyName(43, "arrow_in.png");
            this.FileImageList.Images.SetKeyName(44, "arrow_inout.png");
            this.FileImageList.Images.SetKeyName(45, "arrow_join.png");
            this.FileImageList.Images.SetKeyName(46, "arrow_left.png");
            this.FileImageList.Images.SetKeyName(47, "arrow_merge.png");
            this.FileImageList.Images.SetKeyName(48, "arrow_out.png");
            this.FileImageList.Images.SetKeyName(49, "arrow_redo.png");
            this.FileImageList.Images.SetKeyName(50, "arrow_refresh.png");
            this.FileImageList.Images.SetKeyName(51, "arrow_refresh_small.png");
            this.FileImageList.Images.SetKeyName(52, "arrow_right.png");
            this.FileImageList.Images.SetKeyName(53, "arrow_rotate_anticlockwise.png");
            this.FileImageList.Images.SetKeyName(54, "arrow_rotate_clockwise.png");
            this.FileImageList.Images.SetKeyName(55, "arrow_switch.png");
            this.FileImageList.Images.SetKeyName(56, "arrow_turn_left.png");
            this.FileImageList.Images.SetKeyName(57, "arrow_turn_right.png");
            this.FileImageList.Images.SetKeyName(58, "arrow_undo.png");
            this.FileImageList.Images.SetKeyName(59, "arrow_up.png");
            this.FileImageList.Images.SetKeyName(60, "asterisk_orange.png");
            this.FileImageList.Images.SetKeyName(61, "asterisk_yellow.png");
            this.FileImageList.Images.SetKeyName(62, "attach.png");
            this.FileImageList.Images.SetKeyName(63, "award_star_add.png");
            this.FileImageList.Images.SetKeyName(64, "award_star_bronze_1.png");
            this.FileImageList.Images.SetKeyName(65, "award_star_bronze_2.png");
            this.FileImageList.Images.SetKeyName(66, "award_star_bronze_3.png");
            this.FileImageList.Images.SetKeyName(67, "award_star_delete.png");
            this.FileImageList.Images.SetKeyName(68, "award_star_gold_1.png");
            this.FileImageList.Images.SetKeyName(69, "award_star_gold_2.png");
            this.FileImageList.Images.SetKeyName(70, "award_star_gold_3.png");
            this.FileImageList.Images.SetKeyName(71, "award_star_silver_1.png");
            this.FileImageList.Images.SetKeyName(72, "award_star_silver_2.png");
            this.FileImageList.Images.SetKeyName(73, "award_star_silver_3.png");
            this.FileImageList.Images.SetKeyName(74, "basket.png");
            this.FileImageList.Images.SetKeyName(75, "basket_add.png");
            this.FileImageList.Images.SetKeyName(76, "basket_delete.png");
            this.FileImageList.Images.SetKeyName(77, "basket_edit.png");
            this.FileImageList.Images.SetKeyName(78, "basket_error.png");
            this.FileImageList.Images.SetKeyName(79, "basket_go.png");
            this.FileImageList.Images.SetKeyName(80, "basket_put.png");
            this.FileImageList.Images.SetKeyName(81, "basket_remove.png");
            this.FileImageList.Images.SetKeyName(82, "bell.png");
            this.FileImageList.Images.SetKeyName(83, "bell_add.png");
            this.FileImageList.Images.SetKeyName(84, "bell_delete.png");
            this.FileImageList.Images.SetKeyName(85, "bell_error.png");
            this.FileImageList.Images.SetKeyName(86, "bell_go.png");
            this.FileImageList.Images.SetKeyName(87, "bell_link.png");
            this.FileImageList.Images.SetKeyName(88, "bin.png");
            this.FileImageList.Images.SetKeyName(89, "bin_closed.png");
            this.FileImageList.Images.SetKeyName(90, "bin_empty.png");
            this.FileImageList.Images.SetKeyName(91, "bomb.png");
            this.FileImageList.Images.SetKeyName(92, "book.png");
            this.FileImageList.Images.SetKeyName(93, "book_add.png");
            this.FileImageList.Images.SetKeyName(94, "book_addresses.png");
            this.FileImageList.Images.SetKeyName(95, "book_delete.png");
            this.FileImageList.Images.SetKeyName(96, "book_edit.png");
            this.FileImageList.Images.SetKeyName(97, "book_error.png");
            this.FileImageList.Images.SetKeyName(98, "book_go.png");
            this.FileImageList.Images.SetKeyName(99, "book_key.png");
            this.FileImageList.Images.SetKeyName(100, "book_link.png");
            this.FileImageList.Images.SetKeyName(101, "book_next.png");
            this.FileImageList.Images.SetKeyName(102, "book_open.png");
            this.FileImageList.Images.SetKeyName(103, "book_previous.png");
            this.FileImageList.Images.SetKeyName(104, "box.png");
            this.FileImageList.Images.SetKeyName(105, "brick.png");
            this.FileImageList.Images.SetKeyName(106, "brick_add.png");
            this.FileImageList.Images.SetKeyName(107, "brick_delete.png");
            this.FileImageList.Images.SetKeyName(108, "brick_edit.png");
            this.FileImageList.Images.SetKeyName(109, "brick_error.png");
            this.FileImageList.Images.SetKeyName(110, "brick_go.png");
            this.FileImageList.Images.SetKeyName(111, "brick_link.png");
            this.FileImageList.Images.SetKeyName(112, "bricks.png");
            this.FileImageList.Images.SetKeyName(113, "briefcase.png");
            this.FileImageList.Images.SetKeyName(114, "bug.png");
            this.FileImageList.Images.SetKeyName(115, "bug_add.png");
            this.FileImageList.Images.SetKeyName(116, "bug_delete.png");
            this.FileImageList.Images.SetKeyName(117, "bug_edit.png");
            this.FileImageList.Images.SetKeyName(118, "bug_error.png");
            this.FileImageList.Images.SetKeyName(119, "bug_go.png");
            this.FileImageList.Images.SetKeyName(120, "bug_link.png");
            this.FileImageList.Images.SetKeyName(121, "building.png");
            this.FileImageList.Images.SetKeyName(122, "building_add.png");
            this.FileImageList.Images.SetKeyName(123, "building_delete.png");
            this.FileImageList.Images.SetKeyName(124, "building_edit.png");
            this.FileImageList.Images.SetKeyName(125, "building_error.png");
            this.FileImageList.Images.SetKeyName(126, "building_go.png");
            this.FileImageList.Images.SetKeyName(127, "building_key.png");
            this.FileImageList.Images.SetKeyName(128, "building_link.png");
            this.FileImageList.Images.SetKeyName(129, "bullet_add.png");
            this.FileImageList.Images.SetKeyName(130, "bullet_arrow_bottom.png");
            this.FileImageList.Images.SetKeyName(131, "bullet_arrow_down.png");
            this.FileImageList.Images.SetKeyName(132, "bullet_arrow_top.png");
            this.FileImageList.Images.SetKeyName(133, "bullet_arrow_up.png");
            this.FileImageList.Images.SetKeyName(134, "bullet_black.png");
            this.FileImageList.Images.SetKeyName(135, "bullet_blue.png");
            this.FileImageList.Images.SetKeyName(136, "bullet_delete.png");
            this.FileImageList.Images.SetKeyName(137, "bullet_disk.png");
            this.FileImageList.Images.SetKeyName(138, "bullet_error.png");
            this.FileImageList.Images.SetKeyName(139, "bullet_feed.png");
            this.FileImageList.Images.SetKeyName(140, "bullet_go.png");
            this.FileImageList.Images.SetKeyName(141, "bullet_green.png");
            this.FileImageList.Images.SetKeyName(142, "bullet_key.png");
            this.FileImageList.Images.SetKeyName(143, "bullet_orange.png");
            this.FileImageList.Images.SetKeyName(144, "bullet_picture.png");
            this.FileImageList.Images.SetKeyName(145, "bullet_pink.png");
            this.FileImageList.Images.SetKeyName(146, "bullet_purple.png");
            this.FileImageList.Images.SetKeyName(147, "bullet_red.png");
            this.FileImageList.Images.SetKeyName(148, "bullet_star.png");
            this.FileImageList.Images.SetKeyName(149, "bullet_toggle_minus.png");
            this.FileImageList.Images.SetKeyName(150, "bullet_toggle_plus.png");
            this.FileImageList.Images.SetKeyName(151, "bullet_white.png");
            this.FileImageList.Images.SetKeyName(152, "bullet_wrench.png");
            this.FileImageList.Images.SetKeyName(153, "bullet_yellow.png");
            this.FileImageList.Images.SetKeyName(154, "cake.png");
            this.FileImageList.Images.SetKeyName(155, "calculator.png");
            this.FileImageList.Images.SetKeyName(156, "calculator_add.png");
            this.FileImageList.Images.SetKeyName(157, "calculator_delete.png");
            this.FileImageList.Images.SetKeyName(158, "calculator_edit.png");
            this.FileImageList.Images.SetKeyName(159, "calculator_error.png");
            this.FileImageList.Images.SetKeyName(160, "calculator_link.png");
            this.FileImageList.Images.SetKeyName(161, "calendar.png");
            this.FileImageList.Images.SetKeyName(162, "calendar_add.png");
            this.FileImageList.Images.SetKeyName(163, "calendar_delete.png");
            this.FileImageList.Images.SetKeyName(164, "calendar_edit.png");
            this.FileImageList.Images.SetKeyName(165, "calendar_link.png");
            this.FileImageList.Images.SetKeyName(166, "calendar_view_day.png");
            this.FileImageList.Images.SetKeyName(167, "calendar_view_month.png");
            this.FileImageList.Images.SetKeyName(168, "calendar_view_week.png");
            this.FileImageList.Images.SetKeyName(169, "camera.png");
            this.FileImageList.Images.SetKeyName(170, "camera_add.png");
            this.FileImageList.Images.SetKeyName(171, "camera_delete.png");
            this.FileImageList.Images.SetKeyName(172, "camera_edit.png");
            this.FileImageList.Images.SetKeyName(173, "camera_error.png");
            this.FileImageList.Images.SetKeyName(174, "camera_go.png");
            this.FileImageList.Images.SetKeyName(175, "camera_link.png");
            this.FileImageList.Images.SetKeyName(176, "camera_small.png");
            this.FileImageList.Images.SetKeyName(177, "cancel.png");
            this.FileImageList.Images.SetKeyName(178, "car.png");
            this.FileImageList.Images.SetKeyName(179, "car_add.png");
            this.FileImageList.Images.SetKeyName(180, "car_delete.png");
            this.FileImageList.Images.SetKeyName(181, "cart.png");
            this.FileImageList.Images.SetKeyName(182, "cart_add.png");
            this.FileImageList.Images.SetKeyName(183, "cart_delete.png");
            this.FileImageList.Images.SetKeyName(184, "cart_edit.png");
            this.FileImageList.Images.SetKeyName(185, "cart_error.png");
            this.FileImageList.Images.SetKeyName(186, "cart_go.png");
            this.FileImageList.Images.SetKeyName(187, "cart_put.png");
            this.FileImageList.Images.SetKeyName(188, "cart_remove.png");
            this.FileImageList.Images.SetKeyName(189, "cd.png");
            this.FileImageList.Images.SetKeyName(190, "cd_add.png");
            this.FileImageList.Images.SetKeyName(191, "cd_burn.png");
            this.FileImageList.Images.SetKeyName(192, "cd_delete.png");
            this.FileImageList.Images.SetKeyName(193, "cd_edit.png");
            this.FileImageList.Images.SetKeyName(194, "cd_eject.png");
            this.FileImageList.Images.SetKeyName(195, "cd_go.png");
            this.FileImageList.Images.SetKeyName(196, "chart_bar.png");
            this.FileImageList.Images.SetKeyName(197, "chart_bar_add.png");
            this.FileImageList.Images.SetKeyName(198, "chart_bar_delete.png");
            this.FileImageList.Images.SetKeyName(199, "chart_bar_edit.png");
            this.FileImageList.Images.SetKeyName(200, "chart_bar_error.png");
            this.FileImageList.Images.SetKeyName(201, "chart_bar_link.png");
            this.FileImageList.Images.SetKeyName(202, "chart_curve.png");
            this.FileImageList.Images.SetKeyName(203, "chart_curve_add.png");
            this.FileImageList.Images.SetKeyName(204, "chart_curve_delete.png");
            this.FileImageList.Images.SetKeyName(205, "chart_curve_edit.png");
            this.FileImageList.Images.SetKeyName(206, "chart_curve_error.png");
            this.FileImageList.Images.SetKeyName(207, "chart_curve_go.png");
            this.FileImageList.Images.SetKeyName(208, "chart_curve_link.png");
            this.FileImageList.Images.SetKeyName(209, "chart_line.png");
            this.FileImageList.Images.SetKeyName(210, "chart_line_add.png");
            this.FileImageList.Images.SetKeyName(211, "chart_line_delete.png");
            this.FileImageList.Images.SetKeyName(212, "chart_line_edit.png");
            this.FileImageList.Images.SetKeyName(213, "chart_line_error.png");
            this.FileImageList.Images.SetKeyName(214, "chart_line_link.png");
            this.FileImageList.Images.SetKeyName(215, "chart_organisation.png");
            this.FileImageList.Images.SetKeyName(216, "chart_organisation_add.png");
            this.FileImageList.Images.SetKeyName(217, "chart_organisation_delete.png");
            this.FileImageList.Images.SetKeyName(218, "chart_pie.png");
            this.FileImageList.Images.SetKeyName(219, "chart_pie_add.png");
            this.FileImageList.Images.SetKeyName(220, "chart_pie_delete.png");
            this.FileImageList.Images.SetKeyName(221, "chart_pie_edit.png");
            this.FileImageList.Images.SetKeyName(222, "chart_pie_error.png");
            this.FileImageList.Images.SetKeyName(223, "chart_pie_link.png");
            this.FileImageList.Images.SetKeyName(224, "clock.png");
            this.FileImageList.Images.SetKeyName(225, "clock_add.png");
            this.FileImageList.Images.SetKeyName(226, "clock_delete.png");
            this.FileImageList.Images.SetKeyName(227, "clock_edit.png");
            this.FileImageList.Images.SetKeyName(228, "clock_error.png");
            this.FileImageList.Images.SetKeyName(229, "clock_go.png");
            this.FileImageList.Images.SetKeyName(230, "clock_link.png");
            this.FileImageList.Images.SetKeyName(231, "clock_pause.png");
            this.FileImageList.Images.SetKeyName(232, "clock_play.png");
            this.FileImageList.Images.SetKeyName(233, "clock_red.png");
            this.FileImageList.Images.SetKeyName(234, "clock_stop.png");
            this.FileImageList.Images.SetKeyName(235, "cog.png");
            this.FileImageList.Images.SetKeyName(236, "cog_add.png");
            this.FileImageList.Images.SetKeyName(237, "cog_delete.png");
            this.FileImageList.Images.SetKeyName(238, "cog_edit.png");
            this.FileImageList.Images.SetKeyName(239, "cog_error.png");
            this.FileImageList.Images.SetKeyName(240, "cog_go.png");
            this.FileImageList.Images.SetKeyName(241, "coins.png");
            this.FileImageList.Images.SetKeyName(242, "coins_add.png");
            this.FileImageList.Images.SetKeyName(243, "coins_delete.png");
            this.FileImageList.Images.SetKeyName(244, "color_swatch.png");
            this.FileImageList.Images.SetKeyName(245, "color_wheel.png");
            this.FileImageList.Images.SetKeyName(246, "comment.png");
            this.FileImageList.Images.SetKeyName(247, "comment_add.png");
            this.FileImageList.Images.SetKeyName(248, "comment_delete.png");
            this.FileImageList.Images.SetKeyName(249, "comment_edit.png");
            this.FileImageList.Images.SetKeyName(250, "comments.png");
            this.FileImageList.Images.SetKeyName(251, "comments_add.png");
            this.FileImageList.Images.SetKeyName(252, "comments_delete.png");
            this.FileImageList.Images.SetKeyName(253, "compress.png");
            this.FileImageList.Images.SetKeyName(254, "computer.png");
            this.FileImageList.Images.SetKeyName(255, "computer_add.png");
            this.FileImageList.Images.SetKeyName(256, "computer_delete.png");
            this.FileImageList.Images.SetKeyName(257, "computer_edit.png");
            this.FileImageList.Images.SetKeyName(258, "computer_error.png");
            this.FileImageList.Images.SetKeyName(259, "computer_go.png");
            this.FileImageList.Images.SetKeyName(260, "computer_key.png");
            this.FileImageList.Images.SetKeyName(261, "computer_link.png");
            this.FileImageList.Images.SetKeyName(262, "connect.png");
            this.FileImageList.Images.SetKeyName(263, "contrast.png");
            this.FileImageList.Images.SetKeyName(264, "contrast_decrease.png");
            this.FileImageList.Images.SetKeyName(265, "contrast_high.png");
            this.FileImageList.Images.SetKeyName(266, "contrast_increase.png");
            this.FileImageList.Images.SetKeyName(267, "contrast_low.png");
            this.FileImageList.Images.SetKeyName(268, "control_eject.png");
            this.FileImageList.Images.SetKeyName(269, "control_eject_blue.png");
            this.FileImageList.Images.SetKeyName(270, "control_end.png");
            this.FileImageList.Images.SetKeyName(271, "control_end_blue.png");
            this.FileImageList.Images.SetKeyName(272, "control_equalizer.png");
            this.FileImageList.Images.SetKeyName(273, "control_equalizer_blue.png");
            this.FileImageList.Images.SetKeyName(274, "control_fastforward.png");
            this.FileImageList.Images.SetKeyName(275, "control_fastforward_blue.png");
            this.FileImageList.Images.SetKeyName(276, "control_pause.png");
            this.FileImageList.Images.SetKeyName(277, "control_pause_blue.png");
            this.FileImageList.Images.SetKeyName(278, "control_play.png");
            this.FileImageList.Images.SetKeyName(279, "control_play_blue.png");
            this.FileImageList.Images.SetKeyName(280, "control_repeat.png");
            this.FileImageList.Images.SetKeyName(281, "control_repeat_blue.png");
            this.FileImageList.Images.SetKeyName(282, "control_rewind.png");
            this.FileImageList.Images.SetKeyName(283, "control_rewind_blue.png");
            this.FileImageList.Images.SetKeyName(284, "control_start.png");
            this.FileImageList.Images.SetKeyName(285, "control_start_blue.png");
            this.FileImageList.Images.SetKeyName(286, "control_stop.png");
            this.FileImageList.Images.SetKeyName(287, "control_stop_blue.png");
            this.FileImageList.Images.SetKeyName(288, "controller.png");
            this.FileImageList.Images.SetKeyName(289, "controller_add.png");
            this.FileImageList.Images.SetKeyName(290, "controller_delete.png");
            this.FileImageList.Images.SetKeyName(291, "controller_error.png");
            this.FileImageList.Images.SetKeyName(292, "creditcards.png");
            this.FileImageList.Images.SetKeyName(293, "cross.png");
            this.FileImageList.Images.SetKeyName(294, "css.png");
            this.FileImageList.Images.SetKeyName(295, "css_add.png");
            this.FileImageList.Images.SetKeyName(296, "css_delete.png");
            this.FileImageList.Images.SetKeyName(297, "css_go.png");
            this.FileImageList.Images.SetKeyName(298, "css_valid.png");
            this.FileImageList.Images.SetKeyName(299, "cup.png");
            this.FileImageList.Images.SetKeyName(300, "cup_add.png");
            this.FileImageList.Images.SetKeyName(301, "cup_delete.png");
            this.FileImageList.Images.SetKeyName(302, "cup_edit.png");
            this.FileImageList.Images.SetKeyName(303, "cup_error.png");
            this.FileImageList.Images.SetKeyName(304, "cup_go.png");
            this.FileImageList.Images.SetKeyName(305, "cup_key.png");
            this.FileImageList.Images.SetKeyName(306, "cup_link.png");
            this.FileImageList.Images.SetKeyName(307, "cursor.png");
            this.FileImageList.Images.SetKeyName(308, "cut.png");
            this.FileImageList.Images.SetKeyName(309, "cut_red.png");
            this.FileImageList.Images.SetKeyName(310, "database.png");
            this.FileImageList.Images.SetKeyName(311, "database_add.png");
            this.FileImageList.Images.SetKeyName(312, "database_connect.png");
            this.FileImageList.Images.SetKeyName(313, "database_delete.png");
            this.FileImageList.Images.SetKeyName(314, "database_edit.png");
            this.FileImageList.Images.SetKeyName(315, "database_error.png");
            this.FileImageList.Images.SetKeyName(316, "database_gear.png");
            this.FileImageList.Images.SetKeyName(317, "database_go.png");
            this.FileImageList.Images.SetKeyName(318, "database_key.png");
            this.FileImageList.Images.SetKeyName(319, "database_lightning.png");
            this.FileImageList.Images.SetKeyName(320, "database_link.png");
            this.FileImageList.Images.SetKeyName(321, "database_refresh.png");
            this.FileImageList.Images.SetKeyName(322, "database_save.png");
            this.FileImageList.Images.SetKeyName(323, "database_table.png");
            this.FileImageList.Images.SetKeyName(324, "date.png");
            this.FileImageList.Images.SetKeyName(325, "date_add.png");
            this.FileImageList.Images.SetKeyName(326, "date_delete.png");
            this.FileImageList.Images.SetKeyName(327, "date_edit.png");
            this.FileImageList.Images.SetKeyName(328, "date_error.png");
            this.FileImageList.Images.SetKeyName(329, "date_go.png");
            this.FileImageList.Images.SetKeyName(330, "date_link.png");
            this.FileImageList.Images.SetKeyName(331, "date_magnify.png");
            this.FileImageList.Images.SetKeyName(332, "date_next.png");
            this.FileImageList.Images.SetKeyName(333, "date_previous.png");
            this.FileImageList.Images.SetKeyName(334, "delete.png");
            this.FileImageList.Images.SetKeyName(335, "disconnect.png");
            this.FileImageList.Images.SetKeyName(336, "disk.png");
            this.FileImageList.Images.SetKeyName(337, "disk_multiple.png");
            this.FileImageList.Images.SetKeyName(338, "door.png");
            this.FileImageList.Images.SetKeyName(339, "door_in.png");
            this.FileImageList.Images.SetKeyName(340, "door_open.png");
            this.FileImageList.Images.SetKeyName(341, "door_out.png");
            this.FileImageList.Images.SetKeyName(342, "drink.png");
            this.FileImageList.Images.SetKeyName(343, "drink_empty.png");
            this.FileImageList.Images.SetKeyName(344, "drive.png");
            this.FileImageList.Images.SetKeyName(345, "drive_add.png");
            this.FileImageList.Images.SetKeyName(346, "drive_burn.png");
            this.FileImageList.Images.SetKeyName(347, "drive_cd.png");
            this.FileImageList.Images.SetKeyName(348, "drive_cd_empty.png");
            this.FileImageList.Images.SetKeyName(349, "drive_delete.png");
            this.FileImageList.Images.SetKeyName(350, "drive_disk.png");
            this.FileImageList.Images.SetKeyName(351, "drive_edit.png");
            this.FileImageList.Images.SetKeyName(352, "drive_error.png");
            this.FileImageList.Images.SetKeyName(353, "drive_go.png");
            this.FileImageList.Images.SetKeyName(354, "drive_key.png");
            this.FileImageList.Images.SetKeyName(355, "drive_link.png");
            this.FileImageList.Images.SetKeyName(356, "drive_magnify.png");
            this.FileImageList.Images.SetKeyName(357, "drive_network.png");
            this.FileImageList.Images.SetKeyName(358, "drive_rename.png");
            this.FileImageList.Images.SetKeyName(359, "drive_user.png");
            this.FileImageList.Images.SetKeyName(360, "drive_web.png");
            this.FileImageList.Images.SetKeyName(361, "dvd.png");
            this.FileImageList.Images.SetKeyName(362, "dvd_add.png");
            this.FileImageList.Images.SetKeyName(363, "dvd_delete.png");
            this.FileImageList.Images.SetKeyName(364, "dvd_edit.png");
            this.FileImageList.Images.SetKeyName(365, "dvd_error.png");
            this.FileImageList.Images.SetKeyName(366, "dvd_go.png");
            this.FileImageList.Images.SetKeyName(367, "dvd_key.png");
            this.FileImageList.Images.SetKeyName(368, "dvd_link.png");
            this.FileImageList.Images.SetKeyName(369, "email.png");
            this.FileImageList.Images.SetKeyName(370, "email_add.png");
            this.FileImageList.Images.SetKeyName(371, "email_attach.png");
            this.FileImageList.Images.SetKeyName(372, "email_delete.png");
            this.FileImageList.Images.SetKeyName(373, "email_edit.png");
            this.FileImageList.Images.SetKeyName(374, "email_error.png");
            this.FileImageList.Images.SetKeyName(375, "email_go.png");
            this.FileImageList.Images.SetKeyName(376, "email_link.png");
            this.FileImageList.Images.SetKeyName(377, "email_open.png");
            this.FileImageList.Images.SetKeyName(378, "email_open_image.png");
            this.FileImageList.Images.SetKeyName(379, "emoticon_evilgrin.png");
            this.FileImageList.Images.SetKeyName(380, "emoticon_grin.png");
            this.FileImageList.Images.SetKeyName(381, "emoticon_happy.png");
            this.FileImageList.Images.SetKeyName(382, "emoticon_smile.png");
            this.FileImageList.Images.SetKeyName(383, "emoticon_surprised.png");
            this.FileImageList.Images.SetKeyName(384, "emoticon_tongue.png");
            this.FileImageList.Images.SetKeyName(385, "emoticon_unhappy.png");
            this.FileImageList.Images.SetKeyName(386, "emoticon_waii.png");
            this.FileImageList.Images.SetKeyName(387, "emoticon_wink.png");
            this.FileImageList.Images.SetKeyName(388, "error.png");
            this.FileImageList.Images.SetKeyName(389, "error_add.png");
            this.FileImageList.Images.SetKeyName(390, "error_delete.png");
            this.FileImageList.Images.SetKeyName(391, "error_go.png");
            this.FileImageList.Images.SetKeyName(392, "exclamation.png");
            this.FileImageList.Images.SetKeyName(393, "eye.png");
            this.FileImageList.Images.SetKeyName(394, "feed.png");
            this.FileImageList.Images.SetKeyName(395, "feed_add.png");
            this.FileImageList.Images.SetKeyName(396, "feed_delete.png");
            this.FileImageList.Images.SetKeyName(397, "feed_disk.png");
            this.FileImageList.Images.SetKeyName(398, "feed_edit.png");
            this.FileImageList.Images.SetKeyName(399, "feed_error.png");
            this.FileImageList.Images.SetKeyName(400, "feed_go.png");
            this.FileImageList.Images.SetKeyName(401, "feed_key.png");
            this.FileImageList.Images.SetKeyName(402, "feed_link.png");
            this.FileImageList.Images.SetKeyName(403, "feed_magnify.png");
            this.FileImageList.Images.SetKeyName(404, "female.png");
            this.FileImageList.Images.SetKeyName(405, "film.png");
            this.FileImageList.Images.SetKeyName(406, "film_add.png");
            this.FileImageList.Images.SetKeyName(407, "film_delete.png");
            this.FileImageList.Images.SetKeyName(408, "film_edit.png");
            this.FileImageList.Images.SetKeyName(409, "film_error.png");
            this.FileImageList.Images.SetKeyName(410, "film_go.png");
            this.FileImageList.Images.SetKeyName(411, "film_key.png");
            this.FileImageList.Images.SetKeyName(412, "film_link.png");
            this.FileImageList.Images.SetKeyName(413, "film_save.png");
            this.FileImageList.Images.SetKeyName(414, "find.png");
            this.FileImageList.Images.SetKeyName(415, "flag_blue.png");
            this.FileImageList.Images.SetKeyName(416, "flag_green.png");
            this.FileImageList.Images.SetKeyName(417, "flag_orange.png");
            this.FileImageList.Images.SetKeyName(418, "flag_pink.png");
            this.FileImageList.Images.SetKeyName(419, "flag_purple.png");
            this.FileImageList.Images.SetKeyName(420, "flag_red.png");
            this.FileImageList.Images.SetKeyName(421, "flag_yellow.png");
            this.FileImageList.Images.SetKeyName(422, "folder.png");
            this.FileImageList.Images.SetKeyName(423, "folder_add.png");
            this.FileImageList.Images.SetKeyName(424, "folder_bell.png");
            this.FileImageList.Images.SetKeyName(425, "folder_brick.png");
            this.FileImageList.Images.SetKeyName(426, "folder_bug.png");
            this.FileImageList.Images.SetKeyName(427, "folder_camera.png");
            this.FileImageList.Images.SetKeyName(428, "folder_database.png");
            this.FileImageList.Images.SetKeyName(429, "folder_delete.png");
            this.FileImageList.Images.SetKeyName(430, "folder_edit.png");
            this.FileImageList.Images.SetKeyName(431, "folder_error.png");
            this.FileImageList.Images.SetKeyName(432, "folder_explore.png");
            this.FileImageList.Images.SetKeyName(433, "folder_feed.png");
            this.FileImageList.Images.SetKeyName(434, "folder_find.png");
            this.FileImageList.Images.SetKeyName(435, "folder_go.png");
            this.FileImageList.Images.SetKeyName(436, "folder_heart.png");
            this.FileImageList.Images.SetKeyName(437, "folder_image.png");
            this.FileImageList.Images.SetKeyName(438, "folder_key.png");
            this.FileImageList.Images.SetKeyName(439, "folder_lightbulb.png");
            this.FileImageList.Images.SetKeyName(440, "folder_link.png");
            this.FileImageList.Images.SetKeyName(441, "folder_magnify.png");
            this.FileImageList.Images.SetKeyName(442, "folder_page.png");
            this.FileImageList.Images.SetKeyName(443, "folder_page_white.png");
            this.FileImageList.Images.SetKeyName(444, "folder_palette.png");
            this.FileImageList.Images.SetKeyName(445, "folder_picture.png");
            this.FileImageList.Images.SetKeyName(446, "folder_star.png");
            this.FileImageList.Images.SetKeyName(447, "folder_table.png");
            this.FileImageList.Images.SetKeyName(448, "folder_user.png");
            this.FileImageList.Images.SetKeyName(449, "folder_wrench.png");
            this.FileImageList.Images.SetKeyName(450, "font.png");
            this.FileImageList.Images.SetKeyName(451, "font_add.png");
            this.FileImageList.Images.SetKeyName(452, "font_delete.png");
            this.FileImageList.Images.SetKeyName(453, "font_go.png");
            this.FileImageList.Images.SetKeyName(454, "group.png");
            this.FileImageList.Images.SetKeyName(455, "group_add.png");
            this.FileImageList.Images.SetKeyName(456, "group_delete.png");
            this.FileImageList.Images.SetKeyName(457, "group_edit.png");
            this.FileImageList.Images.SetKeyName(458, "group_error.png");
            this.FileImageList.Images.SetKeyName(459, "group_gear.png");
            this.FileImageList.Images.SetKeyName(460, "group_go.png");
            this.FileImageList.Images.SetKeyName(461, "group_key.png");
            this.FileImageList.Images.SetKeyName(462, "group_link.png");
            this.FileImageList.Images.SetKeyName(463, "heart.png");
            this.FileImageList.Images.SetKeyName(464, "heart_add.png");
            this.FileImageList.Images.SetKeyName(465, "heart_delete.png");
            this.FileImageList.Images.SetKeyName(466, "help.png");
            this.FileImageList.Images.SetKeyName(467, "hourglass.png");
            this.FileImageList.Images.SetKeyName(468, "hourglass_add.png");
            this.FileImageList.Images.SetKeyName(469, "hourglass_delete.png");
            this.FileImageList.Images.SetKeyName(470, "hourglass_go.png");
            this.FileImageList.Images.SetKeyName(471, "hourglass_link.png");
            this.FileImageList.Images.SetKeyName(472, "house.png");
            this.FileImageList.Images.SetKeyName(473, "house_go.png");
            this.FileImageList.Images.SetKeyName(474, "house_link.png");
            this.FileImageList.Images.SetKeyName(475, "html.png");
            this.FileImageList.Images.SetKeyName(476, "html_add.png");
            this.FileImageList.Images.SetKeyName(477, "html_delete.png");
            this.FileImageList.Images.SetKeyName(478, "html_go.png");
            this.FileImageList.Images.SetKeyName(479, "html_valid.png");
            this.FileImageList.Images.SetKeyName(480, "image.png");
            this.FileImageList.Images.SetKeyName(481, "image_add.png");
            this.FileImageList.Images.SetKeyName(482, "image_delete.png");
            this.FileImageList.Images.SetKeyName(483, "image_edit.png");
            this.FileImageList.Images.SetKeyName(484, "image_link.png");
            this.FileImageList.Images.SetKeyName(485, "images.png");
            this.FileImageList.Images.SetKeyName(486, "information.png");
            this.FileImageList.Images.SetKeyName(487, "ipod.png");
            this.FileImageList.Images.SetKeyName(488, "ipod_cast.png");
            this.FileImageList.Images.SetKeyName(489, "ipod_cast_add.png");
            this.FileImageList.Images.SetKeyName(490, "ipod_cast_delete.png");
            this.FileImageList.Images.SetKeyName(491, "ipod_sound.png");
            this.FileImageList.Images.SetKeyName(492, "joystick.png");
            this.FileImageList.Images.SetKeyName(493, "joystick_add.png");
            this.FileImageList.Images.SetKeyName(494, "joystick_delete.png");
            this.FileImageList.Images.SetKeyName(495, "joystick_error.png");
            this.FileImageList.Images.SetKeyName(496, "key.png");
            this.FileImageList.Images.SetKeyName(497, "key_add.png");
            this.FileImageList.Images.SetKeyName(498, "key_delete.png");
            this.FileImageList.Images.SetKeyName(499, "key_go.png");
            this.FileImageList.Images.SetKeyName(500, "keyboard.png");
            this.FileImageList.Images.SetKeyName(501, "keyboard_add.png");
            this.FileImageList.Images.SetKeyName(502, "keyboard_delete.png");
            this.FileImageList.Images.SetKeyName(503, "keyboard_magnify.png");
            this.FileImageList.Images.SetKeyName(504, "layers.png");
            this.FileImageList.Images.SetKeyName(505, "layout.png");
            this.FileImageList.Images.SetKeyName(506, "layout_add.png");
            this.FileImageList.Images.SetKeyName(507, "layout_content.png");
            this.FileImageList.Images.SetKeyName(508, "layout_delete.png");
            this.FileImageList.Images.SetKeyName(509, "layout_edit.png");
            this.FileImageList.Images.SetKeyName(510, "layout_error.png");
            this.FileImageList.Images.SetKeyName(511, "layout_header.png");
            this.FileImageList.Images.SetKeyName(512, "layout_link.png");
            this.FileImageList.Images.SetKeyName(513, "layout_sidebar.png");
            this.FileImageList.Images.SetKeyName(514, "lightbulb.png");
            this.FileImageList.Images.SetKeyName(515, "lightbulb_add.png");
            this.FileImageList.Images.SetKeyName(516, "lightbulb_delete.png");
            this.FileImageList.Images.SetKeyName(517, "lightbulb_off.png");
            this.FileImageList.Images.SetKeyName(518, "lightning.png");
            this.FileImageList.Images.SetKeyName(519, "lightning_add.png");
            this.FileImageList.Images.SetKeyName(520, "lightning_delete.png");
            this.FileImageList.Images.SetKeyName(521, "lightning_go.png");
            this.FileImageList.Images.SetKeyName(522, "link.png");
            this.FileImageList.Images.SetKeyName(523, "link_add.png");
            this.FileImageList.Images.SetKeyName(524, "link_break.png");
            this.FileImageList.Images.SetKeyName(525, "link_delete.png");
            this.FileImageList.Images.SetKeyName(526, "link_edit.png");
            this.FileImageList.Images.SetKeyName(527, "link_error.png");
            this.FileImageList.Images.SetKeyName(528, "link_go.png");
            this.FileImageList.Images.SetKeyName(529, "lock.png");
            this.FileImageList.Images.SetKeyName(530, "lock_add.png");
            this.FileImageList.Images.SetKeyName(531, "lock_break.png");
            this.FileImageList.Images.SetKeyName(532, "lock_delete.png");
            this.FileImageList.Images.SetKeyName(533, "lock_edit.png");
            this.FileImageList.Images.SetKeyName(534, "lock_go.png");
            this.FileImageList.Images.SetKeyName(535, "lock_open.png");
            this.FileImageList.Images.SetKeyName(536, "lorry.png");
            this.FileImageList.Images.SetKeyName(537, "lorry_add.png");
            this.FileImageList.Images.SetKeyName(538, "lorry_delete.png");
            this.FileImageList.Images.SetKeyName(539, "lorry_error.png");
            this.FileImageList.Images.SetKeyName(540, "lorry_flatbed.png");
            this.FileImageList.Images.SetKeyName(541, "lorry_go.png");
            this.FileImageList.Images.SetKeyName(542, "lorry_link.png");
            this.FileImageList.Images.SetKeyName(543, "magifier_zoom_out.png");
            this.FileImageList.Images.SetKeyName(544, "magnifier.png");
            this.FileImageList.Images.SetKeyName(545, "magnifier_zoom_in.png");
            this.FileImageList.Images.SetKeyName(546, "male.png");
            this.FileImageList.Images.SetKeyName(547, "map.png");
            this.FileImageList.Images.SetKeyName(548, "map_add.png");
            this.FileImageList.Images.SetKeyName(549, "map_delete.png");
            this.FileImageList.Images.SetKeyName(550, "map_edit.png");
            this.FileImageList.Images.SetKeyName(551, "map_go.png");
            this.FileImageList.Images.SetKeyName(552, "map_magnify.png");
            this.FileImageList.Images.SetKeyName(553, "medal_bronze_1.png");
            this.FileImageList.Images.SetKeyName(554, "medal_bronze_2.png");
            this.FileImageList.Images.SetKeyName(555, "medal_bronze_3.png");
            this.FileImageList.Images.SetKeyName(556, "medal_bronze_add.png");
            this.FileImageList.Images.SetKeyName(557, "medal_bronze_delete.png");
            this.FileImageList.Images.SetKeyName(558, "medal_gold_1.png");
            this.FileImageList.Images.SetKeyName(559, "medal_gold_2.png");
            this.FileImageList.Images.SetKeyName(560, "medal_gold_3.png");
            this.FileImageList.Images.SetKeyName(561, "medal_gold_add.png");
            this.FileImageList.Images.SetKeyName(562, "medal_gold_delete.png");
            this.FileImageList.Images.SetKeyName(563, "medal_silver_1.png");
            this.FileImageList.Images.SetKeyName(564, "medal_silver_2.png");
            this.FileImageList.Images.SetKeyName(565, "medal_silver_3.png");
            this.FileImageList.Images.SetKeyName(566, "medal_silver_add.png");
            this.FileImageList.Images.SetKeyName(567, "medal_silver_delete.png");
            this.FileImageList.Images.SetKeyName(568, "money.png");
            this.FileImageList.Images.SetKeyName(569, "money_add.png");
            this.FileImageList.Images.SetKeyName(570, "money_delete.png");
            this.FileImageList.Images.SetKeyName(571, "money_dollar.png");
            this.FileImageList.Images.SetKeyName(572, "money_euro.png");
            this.FileImageList.Images.SetKeyName(573, "money_pound.png");
            this.FileImageList.Images.SetKeyName(574, "money_yen.png");
            this.FileImageList.Images.SetKeyName(575, "monitor.png");
            this.FileImageList.Images.SetKeyName(576, "monitor_add.png");
            this.FileImageList.Images.SetKeyName(577, "monitor_delete.png");
            this.FileImageList.Images.SetKeyName(578, "monitor_edit.png");
            this.FileImageList.Images.SetKeyName(579, "monitor_error.png");
            this.FileImageList.Images.SetKeyName(580, "monitor_go.png");
            this.FileImageList.Images.SetKeyName(581, "monitor_lightning.png");
            this.FileImageList.Images.SetKeyName(582, "monitor_link.png");
            this.FileImageList.Images.SetKeyName(583, "mouse.png");
            this.FileImageList.Images.SetKeyName(584, "mouse_add.png");
            this.FileImageList.Images.SetKeyName(585, "mouse_delete.png");
            this.FileImageList.Images.SetKeyName(586, "mouse_error.png");
            this.FileImageList.Images.SetKeyName(587, "music.png");
            this.FileImageList.Images.SetKeyName(588, "new.png");
            this.FileImageList.Images.SetKeyName(589, "newspaper.png");
            this.FileImageList.Images.SetKeyName(590, "newspaper_add.png");
            this.FileImageList.Images.SetKeyName(591, "newspaper_delete.png");
            this.FileImageList.Images.SetKeyName(592, "newspaper_go.png");
            this.FileImageList.Images.SetKeyName(593, "newspaper_link.png");
            this.FileImageList.Images.SetKeyName(594, "note.png");
            this.FileImageList.Images.SetKeyName(595, "note_add.png");
            this.FileImageList.Images.SetKeyName(596, "note_delete.png");
            this.FileImageList.Images.SetKeyName(597, "note_edit.png");
            this.FileImageList.Images.SetKeyName(598, "note_error.png");
            this.FileImageList.Images.SetKeyName(599, "note_go.png");
            this.FileImageList.Images.SetKeyName(600, "overlays.png");
            this.FileImageList.Images.SetKeyName(601, "package.png");
            this.FileImageList.Images.SetKeyName(602, "package_add.png");
            this.FileImageList.Images.SetKeyName(603, "package_delete.png");
            this.FileImageList.Images.SetKeyName(604, "package_go.png");
            this.FileImageList.Images.SetKeyName(605, "package_green.png");
            this.FileImageList.Images.SetKeyName(606, "package_link.png");
            this.FileImageList.Images.SetKeyName(607, "page.png");
            this.FileImageList.Images.SetKeyName(608, "page_add.png");
            this.FileImageList.Images.SetKeyName(609, "page_attach.png");
            this.FileImageList.Images.SetKeyName(610, "page_code.png");
            this.FileImageList.Images.SetKeyName(611, "page_copy.png");
            this.FileImageList.Images.SetKeyName(612, "page_delete.png");
            this.FileImageList.Images.SetKeyName(613, "page_edit.png");
            this.FileImageList.Images.SetKeyName(614, "page_error.png");
            this.FileImageList.Images.SetKeyName(615, "page_excel.png");
            this.FileImageList.Images.SetKeyName(616, "page_find.png");
            this.FileImageList.Images.SetKeyName(617, "page_gear.png");
            this.FileImageList.Images.SetKeyName(618, "page_go.png");
            this.FileImageList.Images.SetKeyName(619, "page_green.png");
            this.FileImageList.Images.SetKeyName(620, "page_key.png");
            this.FileImageList.Images.SetKeyName(621, "page_lightning.png");
            this.FileImageList.Images.SetKeyName(622, "page_link.png");
            this.FileImageList.Images.SetKeyName(623, "page_paintbrush.png");
            this.FileImageList.Images.SetKeyName(624, "page_paste.png");
            this.FileImageList.Images.SetKeyName(625, "page_red.png");
            this.FileImageList.Images.SetKeyName(626, "page_refresh.png");
            this.FileImageList.Images.SetKeyName(627, "page_save.png");
            this.FileImageList.Images.SetKeyName(628, "page_white.png");
            this.FileImageList.Images.SetKeyName(629, "page_white_acrobat.png");
            this.FileImageList.Images.SetKeyName(630, "page_white_actionscript.png");
            this.FileImageList.Images.SetKeyName(631, "page_white_add.png");
            this.FileImageList.Images.SetKeyName(632, "page_white_c.png");
            this.FileImageList.Images.SetKeyName(633, "page_white_camera.png");
            this.FileImageList.Images.SetKeyName(634, "page_white_cd.png");
            this.FileImageList.Images.SetKeyName(635, "page_white_code.png");
            this.FileImageList.Images.SetKeyName(636, "page_white_code_red.png");
            this.FileImageList.Images.SetKeyName(637, "page_white_coldfusion.png");
            this.FileImageList.Images.SetKeyName(638, "page_white_compressed.png");
            this.FileImageList.Images.SetKeyName(639, "page_white_copy.png");
            this.FileImageList.Images.SetKeyName(640, "page_white_cplusplus.png");
            this.FileImageList.Images.SetKeyName(641, "page_white_csharp.png");
            this.FileImageList.Images.SetKeyName(642, "page_white_cup.png");
            this.FileImageList.Images.SetKeyName(643, "page_white_database.png");
            this.FileImageList.Images.SetKeyName(644, "page_white_delete.png");
            this.FileImageList.Images.SetKeyName(645, "page_white_dvd.png");
            this.FileImageList.Images.SetKeyName(646, "page_white_edit.png");
            this.FileImageList.Images.SetKeyName(647, "page_white_error.png");
            this.FileImageList.Images.SetKeyName(648, "page_white_excel.png");
            this.FileImageList.Images.SetKeyName(649, "page_white_find.png");
            this.FileImageList.Images.SetKeyName(650, "page_white_flash.png");
            this.FileImageList.Images.SetKeyName(651, "page_white_freehand.png");
            this.FileImageList.Images.SetKeyName(652, "page_white_gear.png");
            this.FileImageList.Images.SetKeyName(653, "page_white_get.png");
            this.FileImageList.Images.SetKeyName(654, "page_white_go.png");
            this.FileImageList.Images.SetKeyName(655, "page_white_h.png");
            this.FileImageList.Images.SetKeyName(656, "page_white_horizontal.png");
            this.FileImageList.Images.SetKeyName(657, "page_white_key.png");
            this.FileImageList.Images.SetKeyName(658, "page_white_lightning.png");
            this.FileImageList.Images.SetKeyName(659, "page_white_link.png");
            this.FileImageList.Images.SetKeyName(660, "page_white_magnify.png");
            this.FileImageList.Images.SetKeyName(661, "page_white_medal.png");
            this.FileImageList.Images.SetKeyName(662, "page_white_office.png");
            this.FileImageList.Images.SetKeyName(663, "page_white_paint.png");
            this.FileImageList.Images.SetKeyName(664, "page_white_paintbrush.png");
            this.FileImageList.Images.SetKeyName(665, "page_white_paste.png");
            this.FileImageList.Images.SetKeyName(666, "page_white_php.png");
            this.FileImageList.Images.SetKeyName(667, "page_white_picture.png");
            this.FileImageList.Images.SetKeyName(668, "page_white_powerpoint.png");
            this.FileImageList.Images.SetKeyName(669, "page_white_put.png");
            this.FileImageList.Images.SetKeyName(670, "page_white_ruby.png");
            this.FileImageList.Images.SetKeyName(671, "page_white_stack.png");
            this.FileImageList.Images.SetKeyName(672, "page_white_star.png");
            this.FileImageList.Images.SetKeyName(673, "page_white_swoosh.png");
            this.FileImageList.Images.SetKeyName(674, "page_white_text.png");
            this.FileImageList.Images.SetKeyName(675, "page_white_text_width.png");
            this.FileImageList.Images.SetKeyName(676, "page_white_tux.png");
            this.FileImageList.Images.SetKeyName(677, "page_white_vector.png");
            this.FileImageList.Images.SetKeyName(678, "page_white_visualstudio.png");
            this.FileImageList.Images.SetKeyName(679, "page_white_width.png");
            this.FileImageList.Images.SetKeyName(680, "page_white_word.png");
            this.FileImageList.Images.SetKeyName(681, "page_white_world.png");
            this.FileImageList.Images.SetKeyName(682, "page_white_wrench.png");
            this.FileImageList.Images.SetKeyName(683, "page_white_zip.png");
            this.FileImageList.Images.SetKeyName(684, "page_word.png");
            this.FileImageList.Images.SetKeyName(685, "page_world.png");
            this.FileImageList.Images.SetKeyName(686, "paintbrush.png");
            this.FileImageList.Images.SetKeyName(687, "paintcan.png");
            this.FileImageList.Images.SetKeyName(688, "palette.png");
            this.FileImageList.Images.SetKeyName(689, "paste_plain.png");
            this.FileImageList.Images.SetKeyName(690, "paste_word.png");
            this.FileImageList.Images.SetKeyName(691, "pencil.png");
            this.FileImageList.Images.SetKeyName(692, "pencil_add.png");
            this.FileImageList.Images.SetKeyName(693, "pencil_delete.png");
            this.FileImageList.Images.SetKeyName(694, "pencil_go.png");
            this.FileImageList.Images.SetKeyName(695, "phone.png");
            this.FileImageList.Images.SetKeyName(696, "phone_add.png");
            this.FileImageList.Images.SetKeyName(697, "phone_delete.png");
            this.FileImageList.Images.SetKeyName(698, "phone_sound.png");
            this.FileImageList.Images.SetKeyName(699, "photo.png");
            this.FileImageList.Images.SetKeyName(700, "photo_add.png");
            this.FileImageList.Images.SetKeyName(701, "photo_delete.png");
            this.FileImageList.Images.SetKeyName(702, "photo_link.png");
            this.FileImageList.Images.SetKeyName(703, "photos.png");
            this.FileImageList.Images.SetKeyName(704, "picture.png");
            this.FileImageList.Images.SetKeyName(705, "picture_add.png");
            this.FileImageList.Images.SetKeyName(706, "picture_delete.png");
            this.FileImageList.Images.SetKeyName(707, "picture_edit.png");
            this.FileImageList.Images.SetKeyName(708, "picture_empty.png");
            this.FileImageList.Images.SetKeyName(709, "picture_error.png");
            this.FileImageList.Images.SetKeyName(710, "picture_go.png");
            this.FileImageList.Images.SetKeyName(711, "picture_key.png");
            this.FileImageList.Images.SetKeyName(712, "picture_link.png");
            this.FileImageList.Images.SetKeyName(713, "picture_save.png");
            this.FileImageList.Images.SetKeyName(714, "pictures.png");
            this.FileImageList.Images.SetKeyName(715, "pilcrow.png");
            this.FileImageList.Images.SetKeyName(716, "pill.png");
            this.FileImageList.Images.SetKeyName(717, "pill_add.png");
            this.FileImageList.Images.SetKeyName(718, "pill_delete.png");
            this.FileImageList.Images.SetKeyName(719, "pill_go.png");
            this.FileImageList.Images.SetKeyName(720, "plugin.png");
            this.FileImageList.Images.SetKeyName(721, "plugin_add.png");
            this.FileImageList.Images.SetKeyName(722, "plugin_delete.png");
            this.FileImageList.Images.SetKeyName(723, "plugin_disabled.png");
            this.FileImageList.Images.SetKeyName(724, "plugin_edit.png");
            this.FileImageList.Images.SetKeyName(725, "plugin_error.png");
            this.FileImageList.Images.SetKeyName(726, "plugin_go.png");
            this.FileImageList.Images.SetKeyName(727, "plugin_link.png");
            this.FileImageList.Images.SetKeyName(728, "printer.png");
            this.FileImageList.Images.SetKeyName(729, "printer_add.png");
            this.FileImageList.Images.SetKeyName(730, "printer_delete.png");
            this.FileImageList.Images.SetKeyName(731, "printer_empty.png");
            this.FileImageList.Images.SetKeyName(732, "printer_error.png");
            this.FileImageList.Images.SetKeyName(733, "rainbow.png");
            this.FileImageList.Images.SetKeyName(734, "report.png");
            this.FileImageList.Images.SetKeyName(735, "report_add.png");
            this.FileImageList.Images.SetKeyName(736, "report_delete.png");
            this.FileImageList.Images.SetKeyName(737, "report_disk.png");
            this.FileImageList.Images.SetKeyName(738, "report_edit.png");
            this.FileImageList.Images.SetKeyName(739, "report_go.png");
            this.FileImageList.Images.SetKeyName(740, "report_key.png");
            this.FileImageList.Images.SetKeyName(741, "report_link.png");
            this.FileImageList.Images.SetKeyName(742, "report_magnify.png");
            this.FileImageList.Images.SetKeyName(743, "report_picture.png");
            this.FileImageList.Images.SetKeyName(744, "report_user.png");
            this.FileImageList.Images.SetKeyName(745, "report_word.png");
            this.FileImageList.Images.SetKeyName(746, "resultset_first.png");
            this.FileImageList.Images.SetKeyName(747, "resultset_last.png");
            this.FileImageList.Images.SetKeyName(748, "resultset_next.png");
            this.FileImageList.Images.SetKeyName(749, "resultset_previous.png");
            this.FileImageList.Images.SetKeyName(750, "rosette.png");
            this.FileImageList.Images.SetKeyName(751, "rss.png");
            this.FileImageList.Images.SetKeyName(752, "rss_add.png");
            this.FileImageList.Images.SetKeyName(753, "rss_delete.png");
            this.FileImageList.Images.SetKeyName(754, "rss_go.png");
            this.FileImageList.Images.SetKeyName(755, "rss_valid.png");
            this.FileImageList.Images.SetKeyName(756, "ruby.png");
            this.FileImageList.Images.SetKeyName(757, "ruby_add.png");
            this.FileImageList.Images.SetKeyName(758, "ruby_delete.png");
            this.FileImageList.Images.SetKeyName(759, "ruby_gear.png");
            this.FileImageList.Images.SetKeyName(760, "ruby_get.png");
            this.FileImageList.Images.SetKeyName(761, "ruby_go.png");
            this.FileImageList.Images.SetKeyName(762, "ruby_key.png");
            this.FileImageList.Images.SetKeyName(763, "ruby_link.png");
            this.FileImageList.Images.SetKeyName(764, "ruby_put.png");
            this.FileImageList.Images.SetKeyName(765, "script.png");
            this.FileImageList.Images.SetKeyName(766, "script_add.png");
            this.FileImageList.Images.SetKeyName(767, "script_code.png");
            this.FileImageList.Images.SetKeyName(768, "script_code_red.png");
            this.FileImageList.Images.SetKeyName(769, "script_delete.png");
            this.FileImageList.Images.SetKeyName(770, "script_edit.png");
            this.FileImageList.Images.SetKeyName(771, "script_error.png");
            this.FileImageList.Images.SetKeyName(772, "script_gear.png");
            this.FileImageList.Images.SetKeyName(773, "script_go.png");
            this.FileImageList.Images.SetKeyName(774, "script_key.png");
            this.FileImageList.Images.SetKeyName(775, "script_lightning.png");
            this.FileImageList.Images.SetKeyName(776, "script_link.png");
            this.FileImageList.Images.SetKeyName(777, "script_palette.png");
            this.FileImageList.Images.SetKeyName(778, "script_save.png");
            this.FileImageList.Images.SetKeyName(779, "server.png");
            this.FileImageList.Images.SetKeyName(780, "server_add.png");
            this.FileImageList.Images.SetKeyName(781, "server_chart.png");
            this.FileImageList.Images.SetKeyName(782, "server_compressed.png");
            this.FileImageList.Images.SetKeyName(783, "server_connect.png");
            this.FileImageList.Images.SetKeyName(784, "server_database.png");
            this.FileImageList.Images.SetKeyName(785, "server_delete.png");
            this.FileImageList.Images.SetKeyName(786, "server_edit.png");
            this.FileImageList.Images.SetKeyName(787, "server_error.png");
            this.FileImageList.Images.SetKeyName(788, "server_go.png");
            this.FileImageList.Images.SetKeyName(789, "server_key.png");
            this.FileImageList.Images.SetKeyName(790, "server_lightning.png");
            this.FileImageList.Images.SetKeyName(791, "server_link.png");
            this.FileImageList.Images.SetKeyName(792, "server_uncompressed.png");
            this.FileImageList.Images.SetKeyName(793, "shading.png");
            this.FileImageList.Images.SetKeyName(794, "shape_align_bottom.png");
            this.FileImageList.Images.SetKeyName(795, "shape_align_center.png");
            this.FileImageList.Images.SetKeyName(796, "shape_align_left.png");
            this.FileImageList.Images.SetKeyName(797, "shape_align_middle.png");
            this.FileImageList.Images.SetKeyName(798, "shape_align_right.png");
            this.FileImageList.Images.SetKeyName(799, "shape_align_top.png");
            this.FileImageList.Images.SetKeyName(800, "shape_flip_horizontal.png");
            this.FileImageList.Images.SetKeyName(801, "shape_flip_vertical.png");
            this.FileImageList.Images.SetKeyName(802, "shape_group.png");
            this.FileImageList.Images.SetKeyName(803, "shape_handles.png");
            this.FileImageList.Images.SetKeyName(804, "shape_move_back.png");
            this.FileImageList.Images.SetKeyName(805, "shape_move_backwards.png");
            this.FileImageList.Images.SetKeyName(806, "shape_move_forwards.png");
            this.FileImageList.Images.SetKeyName(807, "shape_move_front.png");
            this.FileImageList.Images.SetKeyName(808, "shape_rotate_anticlockwise.png");
            this.FileImageList.Images.SetKeyName(809, "shape_rotate_clockwise.png");
            this.FileImageList.Images.SetKeyName(810, "shape_square.png");
            this.FileImageList.Images.SetKeyName(811, "shape_square_add.png");
            this.FileImageList.Images.SetKeyName(812, "shape_square_delete.png");
            this.FileImageList.Images.SetKeyName(813, "shape_square_edit.png");
            this.FileImageList.Images.SetKeyName(814, "shape_square_error.png");
            this.FileImageList.Images.SetKeyName(815, "shape_square_go.png");
            this.FileImageList.Images.SetKeyName(816, "shape_square_key.png");
            this.FileImageList.Images.SetKeyName(817, "shape_square_link.png");
            this.FileImageList.Images.SetKeyName(818, "shape_ungroup.png");
            this.FileImageList.Images.SetKeyName(819, "shield.png");
            this.FileImageList.Images.SetKeyName(820, "shield_add.png");
            this.FileImageList.Images.SetKeyName(821, "shield_delete.png");
            this.FileImageList.Images.SetKeyName(822, "shield_go.png");
            this.FileImageList.Images.SetKeyName(823, "sitemap.png");
            this.FileImageList.Images.SetKeyName(824, "sitemap_color.png");
            this.FileImageList.Images.SetKeyName(825, "sound.png");
            this.FileImageList.Images.SetKeyName(826, "sound_add.png");
            this.FileImageList.Images.SetKeyName(827, "sound_delete.png");
            this.FileImageList.Images.SetKeyName(828, "sound_low.png");
            this.FileImageList.Images.SetKeyName(829, "sound_mute.png");
            this.FileImageList.Images.SetKeyName(830, "sound_none.png");
            this.FileImageList.Images.SetKeyName(831, "spellcheck.png");
            this.FileImageList.Images.SetKeyName(832, "sport_8ball.png");
            this.FileImageList.Images.SetKeyName(833, "sport_basketball.png");
            this.FileImageList.Images.SetKeyName(834, "sport_football.png");
            this.FileImageList.Images.SetKeyName(835, "sport_golf.png");
            this.FileImageList.Images.SetKeyName(836, "sport_raquet.png");
            this.FileImageList.Images.SetKeyName(837, "sport_shuttlecock.png");
            this.FileImageList.Images.SetKeyName(838, "sport_soccer.png");
            this.FileImageList.Images.SetKeyName(839, "sport_tennis.png");
            this.FileImageList.Images.SetKeyName(840, "star.png");
            this.FileImageList.Images.SetKeyName(841, "status_away.png");
            this.FileImageList.Images.SetKeyName(842, "status_busy.png");
            this.FileImageList.Images.SetKeyName(843, "status_offline.png");
            this.FileImageList.Images.SetKeyName(844, "status_online.png");
            this.FileImageList.Images.SetKeyName(845, "stop.png");
            this.FileImageList.Images.SetKeyName(846, "style.png");
            this.FileImageList.Images.SetKeyName(847, "style_add.png");
            this.FileImageList.Images.SetKeyName(848, "style_delete.png");
            this.FileImageList.Images.SetKeyName(849, "style_edit.png");
            this.FileImageList.Images.SetKeyName(850, "style_go.png");
            this.FileImageList.Images.SetKeyName(851, "sum.png");
            this.FileImageList.Images.SetKeyName(852, "tab.png");
            this.FileImageList.Images.SetKeyName(853, "tab_add.png");
            this.FileImageList.Images.SetKeyName(854, "tab_delete.png");
            this.FileImageList.Images.SetKeyName(855, "tab_edit.png");
            this.FileImageList.Images.SetKeyName(856, "tab_go.png");
            this.FileImageList.Images.SetKeyName(857, "table.png");
            this.FileImageList.Images.SetKeyName(858, "table_add.png");
            this.FileImageList.Images.SetKeyName(859, "table_delete.png");
            this.FileImageList.Images.SetKeyName(860, "table_edit.png");
            this.FileImageList.Images.SetKeyName(861, "table_error.png");
            this.FileImageList.Images.SetKeyName(862, "table_gear.png");
            this.FileImageList.Images.SetKeyName(863, "table_go.png");
            this.FileImageList.Images.SetKeyName(864, "table_key.png");
            this.FileImageList.Images.SetKeyName(865, "table_lightning.png");
            this.FileImageList.Images.SetKeyName(866, "table_link.png");
            this.FileImageList.Images.SetKeyName(867, "table_multiple.png");
            this.FileImageList.Images.SetKeyName(868, "table_refresh.png");
            this.FileImageList.Images.SetKeyName(869, "table_relationship.png");
            this.FileImageList.Images.SetKeyName(870, "table_row_delete.png");
            this.FileImageList.Images.SetKeyName(871, "table_row_insert.png");
            this.FileImageList.Images.SetKeyName(872, "table_save.png");
            this.FileImageList.Images.SetKeyName(873, "table_sort.png");
            this.FileImageList.Images.SetKeyName(874, "tag.png");
            this.FileImageList.Images.SetKeyName(875, "tag_blue.png");
            this.FileImageList.Images.SetKeyName(876, "tag_blue_add.png");
            this.FileImageList.Images.SetKeyName(877, "tag_blue_delete.png");
            this.FileImageList.Images.SetKeyName(878, "tag_blue_edit.png");
            this.FileImageList.Images.SetKeyName(879, "tag_green.png");
            this.FileImageList.Images.SetKeyName(880, "tag_orange.png");
            this.FileImageList.Images.SetKeyName(881, "tag_pink.png");
            this.FileImageList.Images.SetKeyName(882, "tag_purple.png");
            this.FileImageList.Images.SetKeyName(883, "tag_red.png");
            this.FileImageList.Images.SetKeyName(884, "tag_yellow.png");
            this.FileImageList.Images.SetKeyName(885, "telephone.png");
            this.FileImageList.Images.SetKeyName(886, "telephone_add.png");
            this.FileImageList.Images.SetKeyName(887, "telephone_delete.png");
            this.FileImageList.Images.SetKeyName(888, "telephone_edit.png");
            this.FileImageList.Images.SetKeyName(889, "telephone_error.png");
            this.FileImageList.Images.SetKeyName(890, "telephone_go.png");
            this.FileImageList.Images.SetKeyName(891, "telephone_key.png");
            this.FileImageList.Images.SetKeyName(892, "telephone_link.png");
            this.FileImageList.Images.SetKeyName(893, "television.png");
            this.FileImageList.Images.SetKeyName(894, "television_add.png");
            this.FileImageList.Images.SetKeyName(895, "television_delete.png");
            this.FileImageList.Images.SetKeyName(896, "text_align_center.png");
            this.FileImageList.Images.SetKeyName(897, "text_align_justify.png");
            this.FileImageList.Images.SetKeyName(898, "text_align_left.png");
            this.FileImageList.Images.SetKeyName(899, "text_align_right.png");
            this.FileImageList.Images.SetKeyName(900, "text_allcaps.png");
            this.FileImageList.Images.SetKeyName(901, "text_bold.png");
            this.FileImageList.Images.SetKeyName(902, "text_columns.png");
            this.FileImageList.Images.SetKeyName(903, "text_dropcaps.png");
            this.FileImageList.Images.SetKeyName(904, "text_heading_1.png");
            this.FileImageList.Images.SetKeyName(905, "text_heading_2.png");
            this.FileImageList.Images.SetKeyName(906, "text_heading_3.png");
            this.FileImageList.Images.SetKeyName(907, "text_heading_4.png");
            this.FileImageList.Images.SetKeyName(908, "text_heading_5.png");
            this.FileImageList.Images.SetKeyName(909, "text_heading_6.png");
            this.FileImageList.Images.SetKeyName(910, "text_horizontalrule.png");
            this.FileImageList.Images.SetKeyName(911, "text_indent.png");
            this.FileImageList.Images.SetKeyName(912, "text_indent_remove.png");
            this.FileImageList.Images.SetKeyName(913, "text_italic.png");
            this.FileImageList.Images.SetKeyName(914, "text_kerning.png");
            this.FileImageList.Images.SetKeyName(915, "text_letter_omega.png");
            this.FileImageList.Images.SetKeyName(916, "text_letterspacing.png");
            this.FileImageList.Images.SetKeyName(917, "text_linespacing.png");
            this.FileImageList.Images.SetKeyName(918, "text_list_bullets.png");
            this.FileImageList.Images.SetKeyName(919, "text_list_numbers.png");
            this.FileImageList.Images.SetKeyName(920, "text_lowercase.png");
            this.FileImageList.Images.SetKeyName(921, "text_padding_bottom.png");
            this.FileImageList.Images.SetKeyName(922, "text_padding_left.png");
            this.FileImageList.Images.SetKeyName(923, "text_padding_right.png");
            this.FileImageList.Images.SetKeyName(924, "text_padding_top.png");
            this.FileImageList.Images.SetKeyName(925, "text_replace.png");
            this.FileImageList.Images.SetKeyName(926, "text_signature.png");
            this.FileImageList.Images.SetKeyName(927, "text_smallcaps.png");
            this.FileImageList.Images.SetKeyName(928, "text_strikethrough.png");
            this.FileImageList.Images.SetKeyName(929, "text_subscript.png");
            this.FileImageList.Images.SetKeyName(930, "text_superscript.png");
            this.FileImageList.Images.SetKeyName(931, "text_underline.png");
            this.FileImageList.Images.SetKeyName(932, "text_uppercase.png");
            this.FileImageList.Images.SetKeyName(933, "textfield.png");
            this.FileImageList.Images.SetKeyName(934, "textfield_add.png");
            this.FileImageList.Images.SetKeyName(935, "textfield_delete.png");
            this.FileImageList.Images.SetKeyName(936, "textfield_key.png");
            this.FileImageList.Images.SetKeyName(937, "textfield_rename.png");
            this.FileImageList.Images.SetKeyName(938, "thumb_down.png");
            this.FileImageList.Images.SetKeyName(939, "thumb_up.png");
            this.FileImageList.Images.SetKeyName(940, "tick.png");
            this.FileImageList.Images.SetKeyName(941, "time.png");
            this.FileImageList.Images.SetKeyName(942, "time_add.png");
            this.FileImageList.Images.SetKeyName(943, "time_delete.png");
            this.FileImageList.Images.SetKeyName(944, "time_go.png");
            this.FileImageList.Images.SetKeyName(945, "timeline_marker.png");
            this.FileImageList.Images.SetKeyName(946, "transmit.png");
            this.FileImageList.Images.SetKeyName(947, "transmit_add.png");
            this.FileImageList.Images.SetKeyName(948, "transmit_blue.png");
            this.FileImageList.Images.SetKeyName(949, "transmit_delete.png");
            this.FileImageList.Images.SetKeyName(950, "transmit_edit.png");
            this.FileImageList.Images.SetKeyName(951, "transmit_error.png");
            this.FileImageList.Images.SetKeyName(952, "transmit_go.png");
            this.FileImageList.Images.SetKeyName(953, "tux.png");
            this.FileImageList.Images.SetKeyName(954, "user.png");
            this.FileImageList.Images.SetKeyName(955, "user_add.png");
            this.FileImageList.Images.SetKeyName(956, "user_comment.png");
            this.FileImageList.Images.SetKeyName(957, "user_delete.png");
            this.FileImageList.Images.SetKeyName(958, "user_edit.png");
            this.FileImageList.Images.SetKeyName(959, "user_female.png");
            this.FileImageList.Images.SetKeyName(960, "user_go.png");
            this.FileImageList.Images.SetKeyName(961, "user_gray.png");
            this.FileImageList.Images.SetKeyName(962, "user_green.png");
            this.FileImageList.Images.SetKeyName(963, "user_orange.png");
            this.FileImageList.Images.SetKeyName(964, "user_red.png");
            this.FileImageList.Images.SetKeyName(965, "user_suit.png");
            this.FileImageList.Images.SetKeyName(966, "vcard.png");
            this.FileImageList.Images.SetKeyName(967, "vcard_add.png");
            this.FileImageList.Images.SetKeyName(968, "vcard_delete.png");
            this.FileImageList.Images.SetKeyName(969, "vcard_edit.png");
            this.FileImageList.Images.SetKeyName(970, "vector.png");
            this.FileImageList.Images.SetKeyName(971, "vector_add.png");
            this.FileImageList.Images.SetKeyName(972, "vector_delete.png");
            this.FileImageList.Images.SetKeyName(973, "wand.png");
            this.FileImageList.Images.SetKeyName(974, "weather_clouds.png");
            this.FileImageList.Images.SetKeyName(975, "weather_cloudy.png");
            this.FileImageList.Images.SetKeyName(976, "weather_lightning.png");
            this.FileImageList.Images.SetKeyName(977, "weather_rain.png");
            this.FileImageList.Images.SetKeyName(978, "weather_snow.png");
            this.FileImageList.Images.SetKeyName(979, "weather_sun.png");
            this.FileImageList.Images.SetKeyName(980, "webcam.png");
            this.FileImageList.Images.SetKeyName(981, "webcam_add.png");
            this.FileImageList.Images.SetKeyName(982, "webcam_delete.png");
            this.FileImageList.Images.SetKeyName(983, "webcam_error.png");
            this.FileImageList.Images.SetKeyName(984, "world.png");
            this.FileImageList.Images.SetKeyName(985, "world_add.png");
            this.FileImageList.Images.SetKeyName(986, "world_delete.png");
            this.FileImageList.Images.SetKeyName(987, "world_edit.png");
            this.FileImageList.Images.SetKeyName(988, "world_go.png");
            this.FileImageList.Images.SetKeyName(989, "world_link.png");
            this.FileImageList.Images.SetKeyName(990, "wrench.png");
            this.FileImageList.Images.SetKeyName(991, "wrench_orange.png");
            this.FileImageList.Images.SetKeyName(992, "xhtml.png");
            this.FileImageList.Images.SetKeyName(993, "xhtml_add.png");
            this.FileImageList.Images.SetKeyName(994, "xhtml_delete.png");
            this.FileImageList.Images.SetKeyName(995, "xhtml_go.png");
            this.FileImageList.Images.SetKeyName(996, "xhtml_valid.png");
            this.FileImageList.Images.SetKeyName(997, "zoom.png");
            this.FileImageList.Images.SetKeyName(998, "zoom_in.png");
            this.FileImageList.Images.SetKeyName(999, "zoom_out.png");
            // 
            // MainListView
            // 
            this.MainListView.Columns.AddRange(new System.Windows.Forms.ColumnHeader[] {
            this.FileNameColumnHeader,
            this.TypeColumnHeader,
            this.SizeColumnHeader});
            this.MainListView.ContextMenuStrip = this.MainContextMenuStrip;
            this.MainListView.Dock = System.Windows.Forms.DockStyle.Fill;
            this.MainListView.HideSelection = false;
            this.MainListView.Location = new System.Drawing.Point(0, 0);
            this.MainListView.Name = "MainListView";
            this.MainListView.Size = new System.Drawing.Size(530, 379);
            this.MainListView.SmallImageList = this.FileImageList;
            this.MainListView.TabIndex = 0;
            this.MainListView.UseCompatibleStateImageBehavior = false;
            this.MainListView.View = System.Windows.Forms.View.Details;
            this.MainListView.ItemActivate += new System.EventHandler(this.MainListView_ItemActivate);
            this.MainListView.ItemSelectionChanged += new System.Windows.Forms.ListViewItemSelectionChangedEventHandler(this.MainListView_ItemSelectionChanged);
            // 
            // FileNameColumnHeader
            // 
            this.FileNameColumnHeader.Text = "Name";
            this.FileNameColumnHeader.Width = 103;
            // 
            // TypeColumnHeader
            // 
            this.TypeColumnHeader.Text = "Type";
            this.TypeColumnHeader.Width = 103;
            // 
            // SizeColumnHeader
            // 
            this.SizeColumnHeader.Text = "Size";
            this.SizeColumnHeader.Width = 106;
            // 
            // MainContextMenuStrip
            // 
            this.MainContextMenuStrip.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.extractToolStripMenuItem,
            this.viewToolStripMenuItem});
            this.MainContextMenuStrip.Name = "MainContextMenuStrip";
            this.MainContextMenuStrip.Size = new System.Drawing.Size(124, 48);
            // 
            // extractToolStripMenuItem
            // 
            this.extractToolStripMenuItem.Name = "extractToolStripMenuItem";
            this.extractToolStripMenuItem.Size = new System.Drawing.Size(123, 22);
            this.extractToolStripMenuItem.Text = "Extract";
            this.extractToolStripMenuItem.Click += new System.EventHandler(this.extractToolStripMenuItem_Click);
            // 
            // viewToolStripMenuItem
            // 
            this.viewToolStripMenuItem.Name = "viewToolStripMenuItem";
            this.viewToolStripMenuItem.Size = new System.Drawing.Size(123, 22);
            this.viewToolStripMenuItem.Text = "View Hex";
            this.viewToolStripMenuItem.Click += new System.EventHandler(this.viewToolStripMenuItem_Click);
            // 
            // toolStrip1
            // 
            this.toolStrip1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.GoBackButton,
            this.toolStripSeparator1,
            this.PathTextBox,
            this.RefreshButton,
            this.toolStripSeparator2,
            this.SearchTextBox,
            this.SearchButton});
            this.toolStrip1.Location = new System.Drawing.Point(0, 24);
            this.toolStrip1.Name = "toolStrip1";
            this.toolStrip1.Size = new System.Drawing.Size(800, 25);
            this.toolStrip1.TabIndex = 3;
            this.toolStrip1.Text = "toolStrip1";
            // 
            // GoBackButton
            // 
            this.GoBackButton.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
            this.GoBackButton.Image = ((System.Drawing.Image)(resources.GetObject("GoBackButton.Image")));
            this.GoBackButton.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.GoBackButton.Name = "GoBackButton";
            this.GoBackButton.Size = new System.Drawing.Size(23, 22);
            this.GoBackButton.Text = "toolStripButton1";
            this.GoBackButton.Click += new System.EventHandler(this.GoBackButton_Click);
            // 
            // toolStripSeparator1
            // 
            this.toolStripSeparator1.Name = "toolStripSeparator1";
            this.toolStripSeparator1.Size = new System.Drawing.Size(6, 25);
            // 
            // PathTextBox
            // 
            this.PathTextBox.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.PathTextBox.Name = "PathTextBox";
            this.PathTextBox.Size = new System.Drawing.Size(575, 25);
            // 
            // RefreshButton
            // 
            this.RefreshButton.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
            this.RefreshButton.Image = ((System.Drawing.Image)(resources.GetObject("RefreshButton.Image")));
            this.RefreshButton.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.RefreshButton.Name = "RefreshButton";
            this.RefreshButton.Size = new System.Drawing.Size(23, 22);
            this.RefreshButton.Text = "toolStripButton1";
            this.RefreshButton.Click += new System.EventHandler(this.RefreshButton_Click);
            // 
            // toolStripSeparator2
            // 
            this.toolStripSeparator2.Name = "toolStripSeparator2";
            this.toolStripSeparator2.Size = new System.Drawing.Size(6, 25);
            // 
            // SearchTextBox
            // 
            this.SearchTextBox.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.SearchTextBox.Name = "SearchTextBox";
            this.SearchTextBox.Size = new System.Drawing.Size(100, 25);
            this.SearchTextBox.KeyDown += new System.Windows.Forms.KeyEventHandler(this.SearchTextBox_KeyDown);
            // 
            // SearchButton
            // 
            this.SearchButton.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
            this.SearchButton.Image = ((System.Drawing.Image)(resources.GetObject("SearchButton.Image")));
            this.SearchButton.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.SearchButton.Name = "SearchButton";
            this.SearchButton.Size = new System.Drawing.Size(23, 22);
            this.SearchButton.Text = "toolStripButton1";
            this.SearchButton.Click += new System.EventHandler(this.SearchButton_Click);
            // 
            // ExplorerForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(800, 450);
            this.Controls.Add(this.MainSplitContainer);
            this.Controls.Add(this.MainStatusStrip);
            this.Controls.Add(this.toolStrip1);
            this.Controls.Add(this.MainMenuStrip);
            this.Name = "ExplorerForm";
            this.Text = "Explorer  - Skylumz";
            this.MainMenuStrip.ResumeLayout(false);
            this.MainMenuStrip.PerformLayout();
            this.MainStatusStrip.ResumeLayout(false);
            this.MainStatusStrip.PerformLayout();
            this.MainSplitContainer.Panel1.ResumeLayout(false);
            this.MainSplitContainer.Panel2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.MainSplitContainer)).EndInit();
            this.MainSplitContainer.ResumeLayout(false);
            this.MainContextMenuStrip.ResumeLayout(false);
            this.toolStrip1.ResumeLayout(false);
            this.toolStrip1.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        public System.Windows.Forms.MenuStrip MainMenuStrip;
        private System.Windows.Forms.ToolStripMenuItem fileToolStripMenuItem;
        private System.Windows.Forms.StatusStrip MainStatusStrip;
        private System.Windows.Forms.SplitContainer MainSplitContainer;
        private System.Windows.Forms.TreeView MainTreeView;
        private System.Windows.Forms.ColumnHeader FileNameColumnHeader;
        private System.Windows.Forms.ColumnHeader TypeColumnHeader;
        private System.Windows.Forms.ColumnHeader SizeColumnHeader;
        private System.Windows.Forms.ToolStripStatusLabel AmountOfItemsInDirectoryLabel;
        private System.Windows.Forms.ToolStripStatusLabel AmountOfItemsSelectedInListViewLabel;
        private System.Windows.Forms.ImageList FileImageList;
        private System.Windows.Forms.ToolStrip toolStrip1;
        private System.Windows.Forms.ToolStripTextBox SearchTextBox;
        private System.Windows.Forms.ToolStripButton SearchButton;
        private System.Windows.Forms.ToolStripSeparator toolStripSeparator1;
        private System.Windows.Forms.ToolStripButton GoBackButton;
        private System.Windows.Forms.ToolStripSeparator toolStripSeparator2;
        private System.Windows.Forms.ToolStripButton RefreshButton;
        public System.Windows.Forms.ToolStripTextBox PathTextBox;
        private System.Windows.Forms.ContextMenuStrip MainContextMenuStrip;
        private System.Windows.Forms.ToolStripMenuItem extractToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem viewToolStripMenuItem;
        public System.Windows.Forms.ListView MainListView;
    }
}